nginx:
    image: erangaeb/climguards-nginx:0.2
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /private/var/services/climguards/nginx/letsencrypt:/etc/letsencrypt