version: '3.7'
services:
    front:
      container_name: front
      build: ../../front
      image: front:v1.0.0
      networks:
        - my-network
      ports:
        - 80:80
      restart: unless-stopped
      
       
networks:
  my-network:
    name: my-network


    