version: '3.7'
services:
    redis:
      container_name: redis
      networks:
        - my-network
      image: redis:alpine
      volumes:
        - redis_data:/data
      restart: unless-stopped

    api:
      container_name: api
      networks:
        - my-network
      build: ../../api/
      image: api:v1.0.0
      hostname: api
      command: run start
      depends_on:
        - redis
        - postgres
      env_file:
        - ../environnement/.env_api
      restart: unless-stopped
        
      
    
networks:
  my-network:
    name: my-network

volumes:
  redis_data:
    name: redis_data


        

