version: '3.7'
services:
    debian:
      container_name: debian
      networks:
        - my-network
      image: debian:stable-slim
      command: " tail -f /dev/null"
      depends_on:
        - postgres
   
networks:
  my-network:
    name: my-network
