version: '3.7'
services:
    ochalet_redis:
      container_name: ochalet_redis
      networks:
        - ochalet
      image: redis:alpine

    ochalet_postgres:
      container_name: ochalet_postgres
      hostname: ochalet_postgres
      networks:
        - ochalet
      image: postgres:13.4-alpine
      environment:
        - POSTGRES_USER=ochalet
        - POSTGRES_PASSWORD=ochalet
        - POSTGRES_DB=ochalet
      volumes:
        - db_data:/var/lib/postgresql/data

    ochalet_api:
      container_name: ochalet_api
      networks:
        - ochalet
      build: ../api/
      image: ochalet_api:v1.0.0
      command: run dev
      ports:
        - 3000:3000
      depends_on:
        - ochalet_redis
        - ochalet_postgres
      environment:
        - DATABASE_URL=postgres://ochalet:ochalet@ochalet_postgres:5432/ochalet
        - REDIS_TLS_URL=redis://ochalet_redis:6379
        - NODE_ENV=docker
        - PORT=3000


    ochalet_debian:
      container_name: ochalet_debian
      networks:
        - ochalet
      image: debian:stable-slim
      command: " tail -f /dev/null"
      volumes:
        - db_dump:/home/

      
    
networks:
  ochalet:
    name: ochalet

volumes:
  db_dump:
    name: ochalet_db_dump
  db_data:
    name: ochalet_db_data


        

