version: '3.7'
services:
    dump_storage:
      container_name: dump_storage
      image: debian:stable-slim
      command: " tail -f /dev/null"
      volumes:
        - db_dump:/home/:ro
      ports:
        - 3500:3500